name: GitHub Pages

on:
  push:
    branches:
    - main
  
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
        
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.9.5
      with:
        doxyfile-path: "./Doxyfile"
        working-directory: "hardware/design"
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: hardware/design/html
